# Project Overview: NYC Public School SAT Performance Analysis

This project analyzes the performance of New York City (NYC) public schools based on SAT scores. Using the `schools.csv` dataset, the goal is to answer three key questions:

1.  Which NYC schools have the best math results?
2.  What are the top 10 performing schools based on combined SAT scores?
3.  Which single borough has the largest standard deviation in combined SAT scores?

The analysis involves data loading, cleaning, feature engineering (calculating total SAT scores), filtering, sorting, and aggregation to derive insights into school and borough performance.



Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend.

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [ ]:
# Re-run this cell
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

# Start coding here...
# Add as many cells as you like...

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

# Which NYC schools have the best math results?
The best math results are at least 80% of the *maximum possible score of 800* for math

80% of 800 = 0.8 * 800 = 640

Schools with average math scores >= 640

In [ ]:
# subset the schools dataframe for columns school_name and average math, and apply condition to the average_math column
best_math_schools = schools[schools["average_math"] >= 640][["school_name", "average_math"]]
# sort the subsetted dataframe
best_math_schools = best_math_schools.sort_values("average_math", ascending=False)
# Print the result
print (best_math_schools)

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

# What are the top 10 performing schools based on the combined SAT scores?

In [ ]:
# create the new column total_SAT consisting of the total average SAT scores
schools["total_SAT"] = schools["average_math"] + schools["average_reading"] + schools["average_writing"]
schools.head()

                                         school_name  ... total_SAT
0  New Explorations into Science, Technology and ...  ...      1859
1                               Essex Street Academy  ...      1193
2                       Lower Manhattan Arts Academy  ...      1261
3    High School for Dual Language and Asian Studies  ...      1529
4      Henry Street School for International Studies  ...      1197

[5 rows x 8 columns]

In [ ]:
# sort the schools df based on average total SAT scores
schools_sorted = schools.sort_values("total_SAT", ascending=False)
print (schools_sorted)

                                           school_name  ... total_SAT
88                              Stuyvesant High School  ...      2144
170                       Bronx High School of Science  ...      2041
93                 Staten Island Technical High School  ...      2041
174  High School of American Studies at Lehman College  ...      2013
333                        Townsend Harris High School  ...      1981
..                                                 ...  ...       ...
171              Kingsbridge International High School  ...       987
337             Pan American International High School  ...       978
295      International High School at Prospect Heights  ...       946
247                          Multicultural High School  ...       926
182   Pan American International High School at Monroe  ...       924

[375 rows x 8 columns]

In [ ]:
# Subset the schools dataframe for the columns
sub_schools = schools_sorted[["school_name", "total_SAT"]]
print (sub_schools)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
..                                                 ...        ...
171              Kingsbridge International High School        987
337             Pan American International High School        978
295      International High School at Prospect Heights        946
247                          Multicultural High School        926
182   Pan American International High School at Monroe        924

[375 rows x 2 columns]

In [ ]:
# extract the top 10 from the sorted schools dataframe
top_10_schools = sub_schools.head(10)
print (top_10_schools)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

# Which single borough has the largest standard deviation in the combined SAT score?

In [ ]:
import numpy as np

# group the schools df based on borough
grouped_schools = schools.groupby("borough").agg(
    num_schools=('school_name', 'count'),
    average_SAT=('total_SAT', 'mean'),
    std_SAT=('total_SAT', 'std')
).round(2)
print (grouped_schools)

               num_schools  average_SAT  std_SAT
borough
Bronx                   98      1202.72   150.39
Brooklyn               109      1230.26   154.87
Manhattan               89      1340.13   230.29
Queens                  69      1345.48   195.25
Staten Island           10      1439.00   222.30

In [ ]:
largest_std_dev = grouped_schools[grouped_schools["std_SAT"] == grouped_schools["std_SAT"].max()]
print (largest_std_dev)

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29